### PR TITLE
Implement Fly mode from Edocuments and add an additional highlight state

### PR DESCRIPTION
**Pull request by Truning**
Changes/Additions:
- The 'fly' mode from https://github.com/Edocuments/XbimWebUI. (I hope the @Edocuments team agrees to that).
- An additional highlight state (called extraHighlight) that functions like the original highlight state, but its own color can be assigned to it.
-  The svg overlay from the interactive viewer.clip() did not show up if the viewer canvas was in fullscreen mode. (or rather a div containing the viewer canvas was in fullscreen mode). This can be fixed if the svg is also inside that div, thus my suggestion is to insert the svg after the viewer canvas.

### CODE REVIEW

**Comment by GeorgDangl** [comment]
Thank you, looks good for me!

**Comment by GeorgDangl** [comment]
Seems to work fine for me, one issue though: The `canvas` element for the viewer now, by default, seems to show a border when focused. This is solvable by adding a CSS rule like this:

```css
canvas:focus {
    outline: none;
}
```

@Truning, would love to get some feedback!

**Comment by Truning** [comment]
Great! Thank you, @GeorgDangl!

About the border: Did this come from one of my changes? Is your suggestion to add the CSS rule by default in the constructor of the Viewer class?

**Comment by GeorgDangl** [comment]
No, no need to do anything on your side. I just noticed the difference, and it’s always good to have it documented somewhere.

**Pull request merged**
